server:
  port: 8080
  servlet:
    contextPath: /api/msprueba

spring:
  app:
    version: 1.0.0-SNAPSHOT
  application:
    name: MsPrueba
    description: Microservicio prueba java
    base-package: cl.ionix.prueba
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:mem:testdb

des:
  llave: ionix123456

#servicio busqueada
servicio-busqueda:
  url: https://my.api.mockaroo.com/test-tecnico/search/%s
  api-key: f2f719e0
  connect-time-out: 2
  read-time-out: 2

#usuario admin
usuario:
  admin:
    clave: admin
    nombre-usuario: admin