server:
  port: 8080
  servlet:
    contextPath: /api/msprueba

spring:
  app:
    version: 1.0.0-SNAPSHOT
  application:
    name: MsPrueba
    description: Microservicio prueba java
    base-package: cl.ionix.prueba
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:mem:testdb

des:
  llave: ionix123456